server:
  port: 8081

spring:
  application:
    name: ModuloCitas
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modulo_citas
    username: root
    password: 2404
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true


notificaciones:
  url: http://localhost:8000

usuarios:
  url: http://localhost:8080/api