version: '3.8'

services:
  gestion-usuarios-app:
    build: .
    container_name: gestion-usuarios
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/veterinaria_db
      - SPRING_DATA_MONGODB_DATABASE=veterinaria_db
      # Si MongoDB requiere autenticación, descomenta estas líneas:
      # - MONGODB_USERNAME=admin
      # - MONGODB_PASSWORD=password
    depends_on:
      - mongodb
    networks:
      - veterinaria-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: mongodb-veterinaria
    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - veterinaria-network
    restart: unless-stopped

  # Opcional: MongoDB Express para administración web
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-veterinaria
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # Si usas autenticación en MongoDB, descomenta estas líneas:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      # - ME_CONFIG_BASICAUTH_USERNAME=admin
      # - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    networks:
      - veterinaria-network
    restart: unless-stopped

volumes:
  mongodb_data:
  mongodb_config:

networks:
  veterinaria-network:
    driver: bridge