server:
  port: 9000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: usuarios
          uri: lb://usuarios
          predicates:
            - Path=/api/usuarios/**
        - id: tienda_veterinaria
          uri: lb://tienda_veterinaria
          predicates:
            - Path=/api/productos/**
        - id: ModuloPagosStripe
          uri: lb://
          predicates:
            - Path=/api/pagos/**
        - id: ModuloCitas
          uri: lb://modulo_citas
          predicates:
            -Path=/api/modulo_citas/**
        - id: ModuloNotificaciones
          uri: lb://ModuloNotificaciones